#!/usr/bin/env python

import os

env = {}
Import("env")
Import("ssl")

target_path = "../" + env["target_path"] + "/lib"

#if not os.path.isdir(target_path):
#    os.mkdirs(target_path, exist_ok=True)

if env["platform"] == "macos":
    if env["macos_deployment_target"] != "default":
        env.Append(CCFLAGS=["-mmacosx-version-min=" +
                            env["macos_deployment_target"]])
        env.Append(LINKFLAGS=["-mmacosx-version-min=" +
                              env["macos_deployment_target"]])
elif env["platform"] == "windows":
    env.Append(LIBS=["advapi32", "winhttp", "rpcrt4", "crypt32",
               "ole32", "user32", "wsock32", "ws2_32", "bcrypt", "secur32"])

env.Append(CPPPATH=[".", "include/", "src/"])

env.Append(CPPPATH=["#thirdparty/git2/libgit2/include/"])

lib_sources = Glob("src/*.cpp")
env.Depends(lib_sources, ssl)
library = env.SharedLibrary(
    target=target_path + "/{}{}{}".format(env["target_name"], env["suffix"], env["SHLIBSUFFIX"]),
    source=lib_sources
)
library += env.InstallAs(target_path + "/../git_plugin.gdextension", env.File("#misc/git_plugin.gdextension"))
Default(library)
