name: C/C++ CI Tests

on: [push, pull_request]

env:
  # Only used for the cache key. Increment version to force clean build.
  GODOT_BASE_BRANCH: master
  SCONSFLAGS: target=editor build_profile=build_profile.json api_version=4.3
  SCONS_CACHE: ${{ github.workspace }}/.scons-cache/

jobs:
  windows-x64:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Restore Godot build cache
        uses: ./godot-cpp/.github/actions/godot-cache-restore
        with:
          cache-name: windows-x86_64
          scons-cache: ${{ env.SCONS_CACHE }}
        continue-on-error: true
      - uses: ilammy/msvc-dev-cmd@v1  # For dumpbin.
      - uses: ilammy/setup-nasm@v1
      - name: Build for Windows editor x86_64
        shell: powershell
        run: |
          pip3 install scons
          scons platform=windows arch=x86_64
          dumpbin /dependents .\addons\godot-git-plugin\windows\*.dll
      - name: Save Godot build cache
        uses: ./godot-cpp/.github/actions/godot-cache-save
        with:
          cache-name: windows-x86_64
          scons-cache: ${{ env.SCONS_CACHE }}
        continue-on-error: true
      - name: Prepare artifact
        shell: bash
        run: |
          # Not needed to use the plugin.
          rm -f addons/godot-git-plugin/lib/*.{exp,lib}
          mkdir out
          mv addons out/
      - uses: actions/upload-artifact@v7
        with:
          name: libgit_plugin.windows.x86_64.editor.dll-${{ github.sha }}
          if-no-files-found: error
          path: |
            out/
